image: docker:latest

services:
  - docker:dind

build_latest:
  script:
    - sed -i "s/__version__/master @ ${CI_COMMIT_SHORT_SHA}/" config.toml
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest" 
  only:
    - master



pages:
  image: node:latest
  stage: deploy
  script:
    - npm install --progress=false
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
  artifacts:
    expire_in: 1 day
    paths:
      - public
  only:
    - master
